# Generated by Django 4.2.1 on 2023-05-18 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meus_filmes", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filme",
            old_name="lido",
            new_name="assistido",
        ),
    ]
