# Generated by Django 4.2.1 on 2023-05-18 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("meus_filmes", "0002_rename_lido_filme_assistido"),
    ]

    operations = [
        migrations.RenameField(
            model_name="filme",
            old_name="resenha",
            new_name="genero",
        ),
    ]
